
namespace Vista
{
    partial class Ventas
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Ventas));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.dniPK = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnVta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.mail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textprod = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnFinish = new System.Windows.Forms.Button();
            this.cancelBtn = new System.Windows.Forms.Button();
            this.Eliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.searchProd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TotalItems = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.Total = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.cuantity = new System.Windows.Forms.NumericUpDown();
            this.price = new Bunifu.UI.WinForms.BunifuTextBox();
            this.stock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.description = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dataGridDetail = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnLimpiar = new System.Windows.Forms.Button();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cuantity)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridDetail)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnLimpiar);
            this.bunifuPanel1.Controls.Add(this.dniPK);
            this.bunifuPanel1.Controls.Add(this.btnVta);
            this.bunifuPanel1.Controls.Add(this.mail);
            this.bunifuPanel1.Controls.Add(this.name);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1014, 100);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // dniPK
            // 
            this.dniPK.AcceptsReturn = false;
            this.dniPK.AcceptsTab = false;
            this.dniPK.AnimationSpeed = 200;
            this.dniPK.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.dniPK.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.dniPK.AutoSizeHeight = true;
            this.dniPK.BackColor = System.Drawing.Color.Transparent;
            this.dniPK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dniPK.BackgroundImage")));
            this.dniPK.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.dniPK.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dniPK.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.dniPK.BorderColorIdle = System.Drawing.Color.Silver;
            this.dniPK.BorderRadius = 1;
            this.dniPK.BorderThickness = 1;
            this.dniPK.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.dniPK.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.dniPK.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.dniPK.DefaultText = "";
            this.dniPK.FillColor = System.Drawing.Color.White;
            this.dniPK.ForeColor = System.Drawing.Color.Black;
            this.dniPK.HideSelection = true;
            this.dniPK.IconLeft = null;
            this.dniPK.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.dniPK.IconPadding = 10;
            this.dniPK.IconRight = null;
            this.dniPK.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.dniPK.Lines = new string[0];
            this.dniPK.Location = new System.Drawing.Point(23, 28);
            this.dniPK.MaxLength = 32767;
            this.dniPK.MinimumSize = new System.Drawing.Size(1, 1);
            this.dniPK.Modified = false;
            this.dniPK.Multiline = false;
            this.dniPK.Name = "dniPK";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dniPK.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.dniPK.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dniPK.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Black;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dniPK.OnIdleState = stateProperties36;
            this.dniPK.Padding = new System.Windows.Forms.Padding(3);
            this.dniPK.PasswordChar = '\0';
            this.dniPK.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.dniPK.PlaceholderText = "DNI";
            this.dniPK.ReadOnly = false;
            this.dniPK.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dniPK.SelectedText = "";
            this.dniPK.SelectionLength = 0;
            this.dniPK.SelectionStart = 0;
            this.dniPK.ShortcutsEnabled = true;
            this.dniPK.Size = new System.Drawing.Size(218, 39);
            this.dniPK.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.dniPK.TabIndex = 0;
            this.dniPK.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.dniPK.TextMarginBottom = 0;
            this.dniPK.TextMarginLeft = 3;
            this.dniPK.TextMarginTop = 1;
            this.dniPK.TextPlaceholder = "DNI";
            this.dniPK.UseSystemPasswordChar = false;
            this.dniPK.WordWrap = true;
            this.dniPK.KeyDown += new System.Windows.Forms.KeyEventHandler(this.dniPK_KeyDown);
            // 
            // btnVta
            // 
            this.btnVta.AllowAnimations = true;
            this.btnVta.AllowMouseEffects = true;
            this.btnVta.AllowToggling = false;
            this.btnVta.AnimationSpeed = 200;
            this.btnVta.AutoGenerateColors = false;
            this.btnVta.AutoRoundBorders = false;
            this.btnVta.AutoSizeLeftIcon = true;
            this.btnVta.AutoSizeRightIcon = true;
            this.btnVta.BackColor = System.Drawing.Color.Transparent;
            this.btnVta.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnVta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVta.BackgroundImage")));
            this.btnVta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVta.ButtonText = "Crear venta";
            this.btnVta.ButtonTextMarginLeft = 0;
            this.btnVta.ColorContrastOnClick = 45;
            this.btnVta.ColorContrastOnHover = 45;
            this.btnVta.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnVta.CustomizableEdges = borderEdges5;
            this.btnVta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVta.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVta.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnVta.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnVta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnVta.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnVta.ForeColor = System.Drawing.Color.White;
            this.btnVta.IconLeft = null;
            this.btnVta.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVta.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVta.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVta.IconMarginLeft = 11;
            this.btnVta.IconPadding = 10;
            this.btnVta.IconRight = null;
            this.btnVta.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVta.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVta.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVta.IconSize = 25;
            this.btnVta.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnVta.IdleBorderRadius = 0;
            this.btnVta.IdleBorderThickness = 0;
            this.btnVta.IdleFillColor = System.Drawing.Color.Empty;
            this.btnVta.IdleIconLeftImage = null;
            this.btnVta.IdleIconRightImage = null;
            this.btnVta.IndicateFocus = false;
            this.btnVta.Location = new System.Drawing.Point(811, 28);
            this.btnVta.Name = "btnVta";
            this.btnVta.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVta.OnDisabledState.BorderRadius = 1;
            this.btnVta.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVta.OnDisabledState.BorderThickness = 1;
            this.btnVta.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVta.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVta.OnDisabledState.IconLeftImage = null;
            this.btnVta.OnDisabledState.IconRightImage = null;
            this.btnVta.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnVta.onHoverState.BorderRadius = 1;
            this.btnVta.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVta.onHoverState.BorderThickness = 1;
            this.btnVta.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnVta.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVta.onHoverState.IconLeftImage = null;
            this.btnVta.onHoverState.IconRightImage = null;
            this.btnVta.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnVta.OnIdleState.BorderRadius = 1;
            this.btnVta.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVta.OnIdleState.BorderThickness = 1;
            this.btnVta.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnVta.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVta.OnIdleState.IconLeftImage = null;
            this.btnVta.OnIdleState.IconRightImage = null;
            this.btnVta.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVta.OnPressedState.BorderRadius = 1;
            this.btnVta.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVta.OnPressedState.BorderThickness = 1;
            this.btnVta.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVta.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVta.OnPressedState.IconLeftImage = null;
            this.btnVta.OnPressedState.IconRightImage = null;
            this.btnVta.Size = new System.Drawing.Size(150, 39);
            this.btnVta.TabIndex = 36;
            this.btnVta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVta.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVta.TextMarginLeft = 0;
            this.btnVta.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVta.UseDefaultRadiusAndThickness = true;
            this.btnVta.Click += new System.EventHandler(this.btnVta_Click);
            // 
            // mail
            // 
            this.mail.AcceptsReturn = false;
            this.mail.AcceptsTab = false;
            this.mail.AnimationSpeed = 200;
            this.mail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.mail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.mail.AutoSizeHeight = true;
            this.mail.BackColor = System.Drawing.Color.Transparent;
            this.mail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mail.BackgroundImage")));
            this.mail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.mail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.mail.BorderColorIdle = System.Drawing.Color.Silver;
            this.mail.BorderRadius = 1;
            this.mail.BorderThickness = 1;
            this.mail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.mail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.mail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.mail.DefaultText = "";
            this.mail.Enabled = false;
            this.mail.FillColor = System.Drawing.Color.White;
            this.mail.ForeColor = System.Drawing.Color.Black;
            this.mail.HideSelection = true;
            this.mail.IconLeft = null;
            this.mail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.mail.IconPadding = 10;
            this.mail.IconRight = null;
            this.mail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.mail.Lines = new string[0];
            this.mail.Location = new System.Drawing.Point(570, 28);
            this.mail.MaxLength = 32767;
            this.mail.MinimumSize = new System.Drawing.Size(1, 1);
            this.mail.Modified = false;
            this.mail.Multiline = false;
            this.mail.Name = "mail";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mail.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.mail.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mail.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Black;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mail.OnIdleState = stateProperties40;
            this.mail.Padding = new System.Windows.Forms.Padding(3);
            this.mail.PasswordChar = '\0';
            this.mail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.mail.PlaceholderText = "";
            this.mail.ReadOnly = false;
            this.mail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.mail.SelectedText = "";
            this.mail.SelectionLength = 0;
            this.mail.SelectionStart = 0;
            this.mail.ShortcutsEnabled = true;
            this.mail.Size = new System.Drawing.Size(218, 39);
            this.mail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.mail.TabIndex = 2;
            this.mail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.mail.TextMarginBottom = 0;
            this.mail.TextMarginLeft = 3;
            this.mail.TextMarginTop = 1;
            this.mail.TextPlaceholder = "";
            this.mail.UseSystemPasswordChar = false;
            this.mail.WordWrap = true;
            // 
            // name
            // 
            this.name.AcceptsReturn = false;
            this.name.AcceptsTab = false;
            this.name.AnimationSpeed = 200;
            this.name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.name.AutoSizeHeight = true;
            this.name.BackColor = System.Drawing.Color.Transparent;
            this.name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("name.BackgroundImage")));
            this.name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.name.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.name.BorderColorIdle = System.Drawing.Color.Silver;
            this.name.BorderRadius = 1;
            this.name.BorderThickness = 1;
            this.name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.name.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.name.DefaultText = "";
            this.name.Enabled = false;
            this.name.FillColor = System.Drawing.Color.White;
            this.name.ForeColor = System.Drawing.Color.Black;
            this.name.HideSelection = true;
            this.name.IconLeft = null;
            this.name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.name.IconPadding = 10;
            this.name.IconRight = null;
            this.name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.name.Lines = new string[0];
            this.name.Location = new System.Drawing.Point(291, 28);
            this.name.MaxLength = 32767;
            this.name.MinimumSize = new System.Drawing.Size(1, 1);
            this.name.Modified = false;
            this.name.Multiline = false;
            this.name.Name = "name";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.name.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Black;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name.OnIdleState = stateProperties44;
            this.name.Padding = new System.Windows.Forms.Padding(3);
            this.name.PasswordChar = '\0';
            this.name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.name.PlaceholderText = "";
            this.name.ReadOnly = false;
            this.name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.name.SelectedText = "";
            this.name.SelectionLength = 0;
            this.name.SelectionStart = 0;
            this.name.ShortcutsEnabled = true;
            this.name.Size = new System.Drawing.Size(218, 39);
            this.name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.name.TabIndex = 1;
            this.name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.name.TextMarginBottom = 0;
            this.name.TextMarginLeft = 3;
            this.name.TextMarginTop = 1;
            this.name.TextPlaceholder = "";
            this.name.UseSystemPasswordChar = false;
            this.name.WordWrap = true;
            // 
            // textprod
            // 
            this.textprod.AcceptsReturn = false;
            this.textprod.AcceptsTab = false;
            this.textprod.AnimationSpeed = 200;
            this.textprod.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textprod.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textprod.AutoSizeHeight = true;
            this.textprod.BackColor = System.Drawing.Color.Transparent;
            this.textprod.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textprod.BackgroundImage")));
            this.textprod.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textprod.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textprod.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textprod.BorderColorIdle = System.Drawing.Color.Silver;
            this.textprod.BorderRadius = 1;
            this.textprod.BorderThickness = 1;
            this.textprod.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textprod.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textprod.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.textprod.DefaultText = "";
            this.textprod.Enabled = false;
            this.textprod.FillColor = System.Drawing.Color.White;
            this.textprod.ForeColor = System.Drawing.Color.Black;
            this.textprod.HideSelection = true;
            this.textprod.IconLeft = null;
            this.textprod.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textprod.IconPadding = 10;
            this.textprod.IconRight = null;
            this.textprod.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textprod.Lines = new string[0];
            this.textprod.Location = new System.Drawing.Point(23, 26);
            this.textprod.MaxLength = 32767;
            this.textprod.MinimumSize = new System.Drawing.Size(1, 1);
            this.textprod.Modified = false;
            this.textprod.Multiline = false;
            this.textprod.Name = "textprod";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textprod.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textprod.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textprod.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Black;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textprod.OnIdleState = stateProperties48;
            this.textprod.Padding = new System.Windows.Forms.Padding(3);
            this.textprod.PasswordChar = '\0';
            this.textprod.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.textprod.PlaceholderText = "";
            this.textprod.ReadOnly = false;
            this.textprod.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textprod.SelectedText = "";
            this.textprod.SelectionLength = 0;
            this.textprod.SelectionStart = 0;
            this.textprod.ShortcutsEnabled = true;
            this.textprod.Size = new System.Drawing.Size(142, 29);
            this.textprod.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textprod.TabIndex = 3;
            this.textprod.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textprod.TextMarginBottom = 0;
            this.textprod.TextMarginLeft = 3;
            this.textprod.TextMarginTop = 1;
            this.textprod.TextPlaceholder = "";
            this.textprod.UseSystemPasswordChar = false;
            this.textprod.WordWrap = true;
            this.textprod.KeyDown += new System.Windows.Forms.KeyEventHandler(this.textprod_KeyDown);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.btnFinish);
            this.bunifuPanel2.Controls.Add(this.cancelBtn);
            this.bunifuPanel2.Controls.Add(this.Eliminar);
            this.bunifuPanel2.Controls.Add(this.textprod);
            this.bunifuPanel2.Controls.Add(this.searchProd);
            this.bunifuPanel2.Controls.Add(this.addProduct);
            this.bunifuPanel2.Controls.Add(this.TotalItems);
            this.bunifuPanel2.Controls.Add(this.label2);
            this.bunifuPanel2.Controls.Add(this.label1);
            this.bunifuPanel2.Controls.Add(this.Total);
            this.bunifuPanel2.Controls.Add(this.Label12);
            this.bunifuPanel2.Controls.Add(this.label13);
            this.bunifuPanel2.Controls.Add(this.label14);
            this.bunifuPanel2.Controls.Add(this.label15);
            this.bunifuPanel2.Controls.Add(this.label16);
            this.bunifuPanel2.Controls.Add(this.cuantity);
            this.bunifuPanel2.Controls.Add(this.price);
            this.bunifuPanel2.Controls.Add(this.stock);
            this.bunifuPanel2.Controls.Add(this.description);
            this.bunifuPanel2.Controls.Add(this.dataGridDetail);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 100);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(1014, 503);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // btnFinish
            // 
            this.btnFinish.BackColor = System.Drawing.Color.LimeGreen;
            this.btnFinish.Enabled = false;
            this.btnFinish.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(201)))), ((int)(((byte)(209)))), ((int)(((byte)(217)))));
            this.btnFinish.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Lime;
            this.btnFinish.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnFinish.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFinish.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnFinish.ForeColor = System.Drawing.Color.White;
            this.btnFinish.Location = new System.Drawing.Point(758, 440);
            this.btnFinish.Name = "btnFinish";
            this.btnFinish.Size = new System.Drawing.Size(163, 48);
            this.btnFinish.TabIndex = 38;
            this.btnFinish.Text = "Finalizar venta";
            this.btnFinish.UseVisualStyleBackColor = false;
            this.btnFinish.Click += new System.EventHandler(this.btnFinish_Click);
            // 
            // cancelBtn
            // 
            this.cancelBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(10)))), ((int)(((byte)(55)))), ((int)(((byte)(235)))));
            this.cancelBtn.Enabled = false;
            this.cancelBtn.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(201)))), ((int)(((byte)(209)))), ((int)(((byte)(217)))));
            this.cancelBtn.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Red;
            this.cancelBtn.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cancelBtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cancelBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.cancelBtn.ForeColor = System.Drawing.Color.White;
            this.cancelBtn.Location = new System.Drawing.Point(602, 440);
            this.cancelBtn.Name = "cancelBtn";
            this.cancelBtn.Size = new System.Drawing.Size(150, 48);
            this.cancelBtn.TabIndex = 37;
            this.cancelBtn.Text = "Cancelar";
            this.cancelBtn.UseVisualStyleBackColor = false;
            this.cancelBtn.Click += new System.EventHandler(this.cancelBtn_Click);
            // 
            // Eliminar
            // 
            this.Eliminar.AllowAnimations = true;
            this.Eliminar.AllowMouseEffects = true;
            this.Eliminar.AllowToggling = false;
            this.Eliminar.AnimationSpeed = 200;
            this.Eliminar.AutoGenerateColors = false;
            this.Eliminar.AutoRoundBorders = false;
            this.Eliminar.AutoSizeLeftIcon = true;
            this.Eliminar.AutoSizeRightIcon = true;
            this.Eliminar.BackColor = System.Drawing.Color.Transparent;
            this.Eliminar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Eliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Eliminar.BackgroundImage")));
            this.Eliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.ButtonText = "Eliminar";
            this.Eliminar.ButtonTextMarginLeft = 0;
            this.Eliminar.ColorContrastOnClick = 45;
            this.Eliminar.ColorContrastOnHover = 45;
            this.Eliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.Eliminar.CustomizableEdges = borderEdges6;
            this.Eliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Eliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Eliminar.DisabledFillColor = System.Drawing.Color.Empty;
            this.Eliminar.DisabledForecolor = System.Drawing.Color.Empty;
            this.Eliminar.Enabled = false;
            this.Eliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Eliminar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Eliminar.ForeColor = System.Drawing.Color.White;
            this.Eliminar.IconLeft = null;
            this.Eliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Eliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Eliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Eliminar.IconMarginLeft = 11;
            this.Eliminar.IconPadding = 10;
            this.Eliminar.IconRight = null;
            this.Eliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Eliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Eliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Eliminar.IconSize = 25;
            this.Eliminar.IdleBorderColor = System.Drawing.Color.Empty;
            this.Eliminar.IdleBorderRadius = 0;
            this.Eliminar.IdleBorderThickness = 0;
            this.Eliminar.IdleFillColor = System.Drawing.Color.Empty;
            this.Eliminar.IdleIconLeftImage = null;
            this.Eliminar.IdleIconRightImage = null;
            this.Eliminar.IndicateFocus = false;
            this.Eliminar.Location = new System.Drawing.Point(347, 79);
            this.Eliminar.Name = "Eliminar";
            this.Eliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Eliminar.OnDisabledState.BorderRadius = 1;
            this.Eliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.OnDisabledState.BorderThickness = 1;
            this.Eliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Eliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Eliminar.OnDisabledState.IconLeftImage = null;
            this.Eliminar.OnDisabledState.IconRightImage = null;
            this.Eliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.Eliminar.onHoverState.BorderRadius = 1;
            this.Eliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.onHoverState.BorderThickness = 1;
            this.Eliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.Eliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Eliminar.onHoverState.IconLeftImage = null;
            this.Eliminar.onHoverState.IconRightImage = null;
            this.Eliminar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Eliminar.OnIdleState.BorderRadius = 1;
            this.Eliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.OnIdleState.BorderThickness = 1;
            this.Eliminar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Eliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Eliminar.OnIdleState.IconLeftImage = null;
            this.Eliminar.OnIdleState.IconRightImage = null;
            this.Eliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Eliminar.OnPressedState.BorderRadius = 1;
            this.Eliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Eliminar.OnPressedState.BorderThickness = 1;
            this.Eliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Eliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Eliminar.OnPressedState.IconLeftImage = null;
            this.Eliminar.OnPressedState.IconRightImage = null;
            this.Eliminar.Size = new System.Drawing.Size(88, 39);
            this.Eliminar.TabIndex = 36;
            this.Eliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Eliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Eliminar.TextMarginLeft = 0;
            this.Eliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.Eliminar.UseDefaultRadiusAndThickness = true;
            this.Eliminar.Click += new System.EventHandler(this.Eliminar_Click);
            // 
            // searchProd
            // 
            this.searchProd.AllowAnimations = true;
            this.searchProd.AllowMouseEffects = true;
            this.searchProd.AllowToggling = false;
            this.searchProd.AnimationSpeed = 200;
            this.searchProd.AutoGenerateColors = false;
            this.searchProd.AutoRoundBorders = false;
            this.searchProd.AutoSizeLeftIcon = true;
            this.searchProd.AutoSizeRightIcon = true;
            this.searchProd.BackColor = System.Drawing.Color.Transparent;
            this.searchProd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.searchProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchProd.BackgroundImage")));
            this.searchProd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchProd.ButtonText = "Buscar";
            this.searchProd.ButtonTextMarginLeft = 0;
            this.searchProd.ColorContrastOnClick = 45;
            this.searchProd.ColorContrastOnHover = 45;
            this.searchProd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.searchProd.CustomizableEdges = borderEdges7;
            this.searchProd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.searchProd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.searchProd.DisabledFillColor = System.Drawing.Color.Empty;
            this.searchProd.DisabledForecolor = System.Drawing.Color.Empty;
            this.searchProd.Enabled = false;
            this.searchProd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.searchProd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.searchProd.ForeColor = System.Drawing.Color.White;
            this.searchProd.IconLeft = null;
            this.searchProd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.searchProd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.searchProd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.searchProd.IconMarginLeft = 11;
            this.searchProd.IconPadding = 10;
            this.searchProd.IconRight = null;
            this.searchProd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.searchProd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.searchProd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.searchProd.IconSize = 25;
            this.searchProd.IdleBorderColor = System.Drawing.Color.Empty;
            this.searchProd.IdleBorderRadius = 0;
            this.searchProd.IdleBorderThickness = 0;
            this.searchProd.IdleFillColor = System.Drawing.Color.Empty;
            this.searchProd.IdleIconLeftImage = null;
            this.searchProd.IdleIconRightImage = null;
            this.searchProd.IndicateFocus = false;
            this.searchProd.Location = new System.Drawing.Point(684, 26);
            this.searchProd.Name = "searchProd";
            this.searchProd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.searchProd.OnDisabledState.BorderRadius = 1;
            this.searchProd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchProd.OnDisabledState.BorderThickness = 1;
            this.searchProd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchProd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.searchProd.OnDisabledState.IconLeftImage = null;
            this.searchProd.OnDisabledState.IconRightImage = null;
            this.searchProd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.searchProd.onHoverState.BorderRadius = 1;
            this.searchProd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchProd.onHoverState.BorderThickness = 1;
            this.searchProd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.searchProd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.searchProd.onHoverState.IconLeftImage = null;
            this.searchProd.onHoverState.IconRightImage = null;
            this.searchProd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.searchProd.OnIdleState.BorderRadius = 1;
            this.searchProd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchProd.OnIdleState.BorderThickness = 1;
            this.searchProd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.searchProd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.searchProd.OnIdleState.IconLeftImage = null;
            this.searchProd.OnIdleState.IconRightImage = null;
            this.searchProd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.searchProd.OnPressedState.BorderRadius = 1;
            this.searchProd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.searchProd.OnPressedState.BorderThickness = 1;
            this.searchProd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.searchProd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.searchProd.OnPressedState.IconLeftImage = null;
            this.searchProd.OnPressedState.IconRightImage = null;
            this.searchProd.Size = new System.Drawing.Size(86, 29);
            this.searchProd.TabIndex = 34;
            this.searchProd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.searchProd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.searchProd.TextMarginLeft = 0;
            this.searchProd.TextPadding = new System.Windows.Forms.Padding(0);
            this.searchProd.UseDefaultRadiusAndThickness = true;
            this.searchProd.Click += new System.EventHandler(this.searchProd_Click);
            // 
            // addProduct
            // 
            this.addProduct.AllowAnimations = true;
            this.addProduct.AllowMouseEffects = true;
            this.addProduct.AllowToggling = false;
            this.addProduct.AnimationSpeed = 200;
            this.addProduct.AutoGenerateColors = false;
            this.addProduct.AutoRoundBorders = false;
            this.addProduct.AutoSizeLeftIcon = true;
            this.addProduct.AutoSizeRightIcon = true;
            this.addProduct.BackColor = System.Drawing.Color.Transparent;
            this.addProduct.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.addProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addProduct.BackgroundImage")));
            this.addProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProduct.ButtonText = "Agregar";
            this.addProduct.ButtonTextMarginLeft = 0;
            this.addProduct.ColorContrastOnClick = 45;
            this.addProduct.ColorContrastOnHover = 45;
            this.addProduct.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.addProduct.CustomizableEdges = borderEdges8;
            this.addProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addProduct.DisabledFillColor = System.Drawing.Color.Empty;
            this.addProduct.DisabledForecolor = System.Drawing.Color.Empty;
            this.addProduct.Enabled = false;
            this.addProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addProduct.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.addProduct.ForeColor = System.Drawing.Color.White;
            this.addProduct.IconLeft = null;
            this.addProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addProduct.IconMarginLeft = 11;
            this.addProduct.IconPadding = 10;
            this.addProduct.IconRight = null;
            this.addProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addProduct.IconSize = 25;
            this.addProduct.IdleBorderColor = System.Drawing.Color.Empty;
            this.addProduct.IdleBorderRadius = 0;
            this.addProduct.IdleBorderThickness = 0;
            this.addProduct.IdleFillColor = System.Drawing.Color.Empty;
            this.addProduct.IdleIconLeftImage = null;
            this.addProduct.IdleIconRightImage = null;
            this.addProduct.IndicateFocus = false;
            this.addProduct.Location = new System.Drawing.Point(164, 79);
            this.addProduct.Name = "addProduct";
            this.addProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addProduct.OnDisabledState.BorderRadius = 1;
            this.addProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProduct.OnDisabledState.BorderThickness = 1;
            this.addProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addProduct.OnDisabledState.IconLeftImage = null;
            this.addProduct.OnDisabledState.IconRightImage = null;
            this.addProduct.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.addProduct.onHoverState.BorderRadius = 1;
            this.addProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProduct.onHoverState.BorderThickness = 1;
            this.addProduct.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.addProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addProduct.onHoverState.IconLeftImage = null;
            this.addProduct.onHoverState.IconRightImage = null;
            this.addProduct.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.addProduct.OnIdleState.BorderRadius = 1;
            this.addProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProduct.OnIdleState.BorderThickness = 1;
            this.addProduct.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.addProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addProduct.OnIdleState.IconLeftImage = null;
            this.addProduct.OnIdleState.IconRightImage = null;
            this.addProduct.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addProduct.OnPressedState.BorderRadius = 1;
            this.addProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProduct.OnPressedState.BorderThickness = 1;
            this.addProduct.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addProduct.OnPressedState.IconLeftImage = null;
            this.addProduct.OnPressedState.IconRightImage = null;
            this.addProduct.Size = new System.Drawing.Size(150, 39);
            this.addProduct.TabIndex = 33;
            this.addProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addProduct.TextMarginLeft = 0;
            this.addProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.addProduct.UseDefaultRadiusAndThickness = true;
            this.addProduct.Click += new System.EventHandler(this.addProduct_Click_1);
            // 
            // TotalItems
            // 
            this.TotalItems.AutoSize = true;
            this.TotalItems.Location = new System.Drawing.Point(840, 108);
            this.TotalItems.Name = "TotalItems";
            this.TotalItems.Size = new System.Drawing.Size(13, 13);
            this.TotalItems.TabIndex = 32;
            this.TotalItems.Text = "0";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(772, 108);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(62, 13);
            this.label2.TabIndex = 31;
            this.label2.Text = "Total Items:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(49, 457);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(40, 13);
            this.label1.TabIndex = 30;
            this.label1.Text = "Monto:";
            // 
            // Total
            // 
            this.Total.AcceptsReturn = false;
            this.Total.AcceptsTab = false;
            this.Total.AnimationSpeed = 200;
            this.Total.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Total.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Total.AutoSizeHeight = true;
            this.Total.BackColor = System.Drawing.Color.Transparent;
            this.Total.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Total.BackgroundImage")));
            this.Total.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Total.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Total.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Total.BorderColorIdle = System.Drawing.Color.Silver;
            this.Total.BorderRadius = 1;
            this.Total.BorderThickness = 1;
            this.Total.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Total.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Total.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Total.DefaultText = "";
            this.Total.Enabled = false;
            this.Total.FillColor = System.Drawing.Color.White;
            this.Total.ForeColor = System.Drawing.Color.Black;
            this.Total.HideSelection = true;
            this.Total.IconLeft = null;
            this.Total.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Total.IconPadding = 10;
            this.Total.IconRight = null;
            this.Total.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Total.Lines = new string[0];
            this.Total.Location = new System.Drawing.Point(104, 450);
            this.Total.MaxLength = 32767;
            this.Total.MinimumSize = new System.Drawing.Size(1, 1);
            this.Total.Modified = false;
            this.Total.Multiline = false;
            this.Total.Name = "Total";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Total.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Total.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Total.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Black;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Total.OnIdleState = stateProperties52;
            this.Total.Padding = new System.Windows.Forms.Padding(3);
            this.Total.PasswordChar = '\0';
            this.Total.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Total.PlaceholderText = "";
            this.Total.ReadOnly = true;
            this.Total.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Total.SelectedText = "";
            this.Total.SelectionLength = 0;
            this.Total.SelectionStart = 0;
            this.Total.ShortcutsEnabled = true;
            this.Total.Size = new System.Drawing.Size(137, 29);
            this.Total.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Total.TabIndex = 29;
            this.Total.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Total.TextMarginBottom = 0;
            this.Total.TextMarginLeft = 3;
            this.Total.TextMarginTop = 1;
            this.Total.TextPlaceholder = "";
            this.Total.UseSystemPasswordChar = false;
            this.Total.WordWrap = true;
            // 
            // Label12
            // 
            this.Label12.AutoSize = true;
            this.Label12.Location = new System.Drawing.Point(20, 75);
            this.Label12.Name = "Label12";
            this.Label12.Size = new System.Drawing.Size(52, 13);
            this.Label12.TabIndex = 26;
            this.Label12.Text = "Cantidad:";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(531, 10);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(77, 13);
            this.label13.TabIndex = 25;
            this.label13.Text = "Precio Unidad:";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(369, 10);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(38, 13);
            this.label14.TabIndex = 24;
            this.label14.Text = "Stock:";
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(201, 10);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(44, 13);
            this.label15.TabIndex = 23;
            this.label15.Text = "Nombre";
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(20, 10);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(40, 13);
            this.label16.TabIndex = 22;
            this.label16.Text = "Codigo";
            // 
            // cuantity
            // 
            this.cuantity.AutoSize = true;
            this.cuantity.Location = new System.Drawing.Point(23, 91);
            this.cuantity.Name = "cuantity";
            this.cuantity.Size = new System.Drawing.Size(120, 20);
            this.cuantity.TabIndex = 21;
            // 
            // price
            // 
            this.price.AcceptsReturn = false;
            this.price.AcceptsTab = false;
            this.price.AnimationSpeed = 200;
            this.price.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.price.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.price.AutoSizeHeight = true;
            this.price.BackColor = System.Drawing.Color.Transparent;
            this.price.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("price.BackgroundImage")));
            this.price.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.price.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.price.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.price.BorderColorIdle = System.Drawing.Color.Silver;
            this.price.BorderRadius = 1;
            this.price.BorderThickness = 1;
            this.price.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.price.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.price.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.price.DefaultText = "";
            this.price.Enabled = false;
            this.price.FillColor = System.Drawing.Color.White;
            this.price.ForeColor = System.Drawing.Color.Black;
            this.price.HideSelection = true;
            this.price.IconLeft = null;
            this.price.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.price.IconPadding = 10;
            this.price.IconRight = null;
            this.price.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.price.Lines = new string[0];
            this.price.Location = new System.Drawing.Point(534, 26);
            this.price.MaxLength = 32767;
            this.price.MinimumSize = new System.Drawing.Size(1, 1);
            this.price.Modified = false;
            this.price.Multiline = false;
            this.price.Name = "price";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.price.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.price.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.price.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Black;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.price.OnIdleState = stateProperties56;
            this.price.Padding = new System.Windows.Forms.Padding(3);
            this.price.PasswordChar = '\0';
            this.price.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.price.PlaceholderText = "";
            this.price.ReadOnly = false;
            this.price.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.price.SelectedText = "";
            this.price.SelectionLength = 0;
            this.price.SelectionStart = 0;
            this.price.ShortcutsEnabled = true;
            this.price.Size = new System.Drawing.Size(137, 29);
            this.price.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.price.TabIndex = 9;
            this.price.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.price.TextMarginBottom = 0;
            this.price.TextMarginLeft = 3;
            this.price.TextMarginTop = 1;
            this.price.TextPlaceholder = "";
            this.price.UseSystemPasswordChar = false;
            this.price.WordWrap = true;
            // 
            // stock
            // 
            this.stock.AcceptsReturn = false;
            this.stock.AcceptsTab = false;
            this.stock.AnimationSpeed = 200;
            this.stock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.stock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.stock.AutoSizeHeight = true;
            this.stock.BackColor = System.Drawing.Color.Transparent;
            this.stock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("stock.BackgroundImage")));
            this.stock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.stock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.stock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.stock.BorderColorIdle = System.Drawing.Color.Silver;
            this.stock.BorderRadius = 1;
            this.stock.BorderThickness = 1;
            this.stock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.stock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.stock.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.stock.DefaultText = "";
            this.stock.Enabled = false;
            this.stock.FillColor = System.Drawing.Color.White;
            this.stock.ForeColor = System.Drawing.Color.Black;
            this.stock.HideSelection = true;
            this.stock.IconLeft = null;
            this.stock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.stock.IconPadding = 10;
            this.stock.IconRight = null;
            this.stock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.stock.Lines = new string[0];
            this.stock.Location = new System.Drawing.Point(372, 26);
            this.stock.MaxLength = 32767;
            this.stock.MinimumSize = new System.Drawing.Size(1, 1);
            this.stock.Modified = false;
            this.stock.Multiline = false;
            this.stock.Name = "stock";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.stock.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.stock.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.stock.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Black;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.stock.OnIdleState = stateProperties60;
            this.stock.Padding = new System.Windows.Forms.Padding(3);
            this.stock.PasswordChar = '\0';
            this.stock.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.stock.PlaceholderText = "";
            this.stock.ReadOnly = true;
            this.stock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.stock.SelectedText = "";
            this.stock.SelectionLength = 0;
            this.stock.SelectionStart = 0;
            this.stock.ShortcutsEnabled = true;
            this.stock.Size = new System.Drawing.Size(137, 29);
            this.stock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.stock.TabIndex = 8;
            this.stock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.stock.TextMarginBottom = 0;
            this.stock.TextMarginLeft = 3;
            this.stock.TextMarginTop = 1;
            this.stock.TextPlaceholder = "";
            this.stock.UseSystemPasswordChar = false;
            this.stock.WordWrap = true;
            // 
            // description
            // 
            this.description.AcceptsReturn = false;
            this.description.AcceptsTab = false;
            this.description.AnimationSpeed = 200;
            this.description.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.description.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.description.AutoSizeHeight = true;
            this.description.BackColor = System.Drawing.Color.Transparent;
            this.description.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("description.BackgroundImage")));
            this.description.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.description.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.description.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.description.BorderColorIdle = System.Drawing.Color.Silver;
            this.description.BorderRadius = 1;
            this.description.BorderThickness = 1;
            this.description.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.description.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.description.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.description.DefaultText = "";
            this.description.Enabled = false;
            this.description.FillColor = System.Drawing.Color.White;
            this.description.ForeColor = System.Drawing.Color.Black;
            this.description.HideSelection = true;
            this.description.IconLeft = null;
            this.description.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.description.IconPadding = 10;
            this.description.IconRight = null;
            this.description.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.description.Lines = new string[0];
            this.description.Location = new System.Drawing.Point(204, 26);
            this.description.MaxLength = 32767;
            this.description.MinimumSize = new System.Drawing.Size(1, 1);
            this.description.Modified = false;
            this.description.Multiline = false;
            this.description.Name = "description";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.description.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.description.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.description.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Black;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.description.OnIdleState = stateProperties64;
            this.description.Padding = new System.Windows.Forms.Padding(3);
            this.description.PasswordChar = '\0';
            this.description.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.description.PlaceholderText = "";
            this.description.ReadOnly = true;
            this.description.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.description.SelectedText = "";
            this.description.SelectionLength = 0;
            this.description.SelectionStart = 0;
            this.description.ShortcutsEnabled = true;
            this.description.Size = new System.Drawing.Size(137, 29);
            this.description.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.description.TabIndex = 7;
            this.description.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.description.TextMarginBottom = 0;
            this.description.TextMarginLeft = 3;
            this.description.TextMarginTop = 1;
            this.description.TextPlaceholder = "";
            this.description.UseSystemPasswordChar = false;
            this.description.WordWrap = true;
            // 
            // dataGridDetail
            // 
            this.dataGridDetail.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dataGridDetail.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dataGridDetail.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridDetail.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridDetail.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridDetail.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridDetail.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dataGridDetail.ColumnHeadersHeight = 40;
            this.dataGridDetail.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridDetail.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridDetail.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridDetail.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridDetail.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridDetail.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridDetail.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridDetail.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridDetail.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridDetail.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridDetail.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataGridDetail.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridDetail.CurrentTheme.Name = null;
            this.dataGridDetail.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridDetail.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridDetail.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridDetail.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridDetail.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridDetail.DefaultCellStyle = dataGridViewCellStyle6;
            this.dataGridDetail.EnableHeadersVisualStyles = false;
            this.dataGridDetail.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridDetail.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridDetail.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridDetail.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridDetail.Location = new System.Drawing.Point(23, 129);
            this.dataGridDetail.Name = "dataGridDetail";
            this.dataGridDetail.RowHeadersVisible = false;
            this.dataGridDetail.RowTemplate.Height = 40;
            this.dataGridDetail.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridDetail.Size = new System.Drawing.Size(898, 289);
            this.dataGridDetail.TabIndex = 4;
            this.dataGridDetail.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dataGridDetail.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridDetail_CellClick);
            // 
            // btnLimpiar
            // 
            this.btnLimpiar.BackColor = System.Drawing.Color.White;
            this.btnLimpiar.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(201)))), ((int)(((byte)(209)))), ((int)(((byte)(217)))));
            this.btnLimpiar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnLimpiar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Gray;
            this.btnLimpiar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLimpiar.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.btnLimpiar.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.Location = new System.Drawing.Point(247, 28);
            this.btnLimpiar.Name = "btnLimpiar";
            this.btnLimpiar.Size = new System.Drawing.Size(38, 40);
            this.btnLimpiar.TabIndex = 38;
            this.btnLimpiar.Text = "🔎";
            this.btnLimpiar.UseVisualStyleBackColor = false;
            this.btnLimpiar.Click += new System.EventHandler(this.btnLimpiar_Click);
            // 
            // Ventas
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(1014, 603);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.ForeColor = System.Drawing.Color.White;
            this.MaximizeBox = false;
            this.Name = "Ventas";
            this.Text = "Ventas";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cuantity)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridDetail)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox mail;
        private Bunifu.UI.WinForms.BunifuTextBox name;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox dniPK;
        private Bunifu.UI.WinForms.BunifuTextBox description;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridDetail;
        internal System.Windows.Forms.Label TotalItems;
        internal System.Windows.Forms.Label label2;
        internal System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox Total;
        internal System.Windows.Forms.Label Label12;
        internal System.Windows.Forms.Label label13;
        internal System.Windows.Forms.Label label14;
        internal System.Windows.Forms.Label label15;
        internal System.Windows.Forms.Label label16;
        private System.Windows.Forms.NumericUpDown cuantity;
        private Bunifu.UI.WinForms.BunifuTextBox price;
        private Bunifu.UI.WinForms.BunifuTextBox stock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton searchProd;
        private Bunifu.UI.WinForms.BunifuTextBox textprod;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVta;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Eliminar;
        private System.Windows.Forms.Button cancelBtn;
        private System.Windows.Forms.Button btnFinish;
        private System.Windows.Forms.Button btnLimpiar;
    }
}