
namespace Vista
{
    partial class cuenta_corriente
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(cuenta_corriente));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.lblSaldo = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.inputEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.inputDNI = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.inputName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.VentaCC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataMove = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnPay = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.comboSelect = new System.Windows.Forms.ComboBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDatePicker2 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.numberVta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BtnSendEmail = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnPrint = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataMove)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.lblSaldo);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel4);
            this.bunifuGroupBox1.Controls.Add(this.inputEmail);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel3);
            this.bunifuGroupBox1.Controls.Add(this.inputDNI);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel2);
            this.bunifuGroupBox1.Controls.Add(this.inputName);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel1);
            this.bunifuGroupBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(1184, 127);
            this.bunifuGroupBox1.TabIndex = 0;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Datos cuenta corriente";
            // 
            // lblSaldo
            // 
            this.lblSaldo.AllowParentOverrides = false;
            this.lblSaldo.AutoEllipsis = false;
            this.lblSaldo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblSaldo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblSaldo.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblSaldo.Location = new System.Drawing.Point(255, 82);
            this.lblSaldo.Name = "lblSaldo";
            this.lblSaldo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSaldo.Size = new System.Drawing.Size(49, 32);
            this.lblSaldo.TabIndex = 7;
            this.lblSaldo.Text = "0.00";
            this.lblSaldo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSaldo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(12, 82);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(237, 32);
            this.bunifuLabel4.TabIndex = 6;
            this.bunifuLabel4.Text = "Saldo de la cuenta: $";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // inputEmail
            // 
            this.inputEmail.AcceptsReturn = false;
            this.inputEmail.AcceptsTab = false;
            this.inputEmail.AnimationSpeed = 200;
            this.inputEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.inputEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.inputEmail.AutoSizeHeight = true;
            this.inputEmail.BackColor = System.Drawing.Color.Transparent;
            this.inputEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("inputEmail.BackgroundImage")));
            this.inputEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.inputEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.inputEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.inputEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.inputEmail.BorderRadius = 1;
            this.inputEmail.BorderThickness = 1;
            this.inputEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.inputEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.inputEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.inputEmail.DefaultText = "";
            this.inputEmail.Enabled = false;
            this.inputEmail.FillColor = System.Drawing.Color.White;
            this.inputEmail.HideSelection = true;
            this.inputEmail.IconLeft = null;
            this.inputEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.inputEmail.IconPadding = 10;
            this.inputEmail.IconRight = null;
            this.inputEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.inputEmail.Lines = new string[0];
            this.inputEmail.Location = new System.Drawing.Point(828, 37);
            this.inputEmail.MaxLength = 32767;
            this.inputEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.inputEmail.Modified = false;
            this.inputEmail.Multiline = false;
            this.inputEmail.Name = "inputEmail";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputEmail.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.inputEmail.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputEmail.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputEmail.OnIdleState = stateProperties4;
            this.inputEmail.Padding = new System.Windows.Forms.Padding(3);
            this.inputEmail.PasswordChar = '\0';
            this.inputEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.inputEmail.PlaceholderText = "Enter text";
            this.inputEmail.ReadOnly = false;
            this.inputEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.inputEmail.SelectedText = "";
            this.inputEmail.SelectionLength = 0;
            this.inputEmail.SelectionStart = 0;
            this.inputEmail.ShortcutsEnabled = true;
            this.inputEmail.Size = new System.Drawing.Size(210, 39);
            this.inputEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.inputEmail.TabIndex = 5;
            this.inputEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.inputEmail.TextMarginBottom = 0;
            this.inputEmail.TextMarginLeft = 3;
            this.inputEmail.TextMarginTop = 1;
            this.inputEmail.TextPlaceholder = "Enter text";
            this.inputEmail.UseSystemPasswordChar = false;
            this.inputEmail.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(788, 46);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(34, 15);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "EMAIL";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // inputDNI
            // 
            this.inputDNI.AcceptsReturn = false;
            this.inputDNI.AcceptsTab = false;
            this.inputDNI.AnimationSpeed = 200;
            this.inputDNI.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.inputDNI.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.inputDNI.AutoSizeHeight = true;
            this.inputDNI.BackColor = System.Drawing.Color.Transparent;
            this.inputDNI.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("inputDNI.BackgroundImage")));
            this.inputDNI.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.inputDNI.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.inputDNI.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.inputDNI.BorderColorIdle = System.Drawing.Color.Silver;
            this.inputDNI.BorderRadius = 1;
            this.inputDNI.BorderThickness = 1;
            this.inputDNI.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.inputDNI.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.inputDNI.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.inputDNI.DefaultText = "";
            this.inputDNI.Enabled = false;
            this.inputDNI.FillColor = System.Drawing.Color.White;
            this.inputDNI.HideSelection = true;
            this.inputDNI.IconLeft = null;
            this.inputDNI.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.inputDNI.IconPadding = 10;
            this.inputDNI.IconRight = null;
            this.inputDNI.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.inputDNI.Lines = new string[0];
            this.inputDNI.Location = new System.Drawing.Point(532, 37);
            this.inputDNI.MaxLength = 32767;
            this.inputDNI.MinimumSize = new System.Drawing.Size(1, 1);
            this.inputDNI.Modified = false;
            this.inputDNI.Multiline = false;
            this.inputDNI.Name = "inputDNI";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputDNI.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.inputDNI.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputDNI.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputDNI.OnIdleState = stateProperties8;
            this.inputDNI.Padding = new System.Windows.Forms.Padding(3);
            this.inputDNI.PasswordChar = '\0';
            this.inputDNI.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.inputDNI.PlaceholderText = "Enter text";
            this.inputDNI.ReadOnly = false;
            this.inputDNI.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.inputDNI.SelectedText = "";
            this.inputDNI.SelectionLength = 0;
            this.inputDNI.SelectionStart = 0;
            this.inputDNI.ShortcutsEnabled = true;
            this.inputDNI.Size = new System.Drawing.Size(199, 39);
            this.inputDNI.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.inputDNI.TabIndex = 3;
            this.inputDNI.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.inputDNI.TextMarginBottom = 0;
            this.inputDNI.TextMarginLeft = 3;
            this.inputDNI.TextMarginTop = 1;
            this.inputDNI.TextPlaceholder = "Enter text";
            this.inputDNI.UseSystemPasswordChar = false;
            this.inputDNI.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(489, 46);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(20, 15);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "DNI";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // inputName
            // 
            this.inputName.AcceptsReturn = false;
            this.inputName.AcceptsTab = false;
            this.inputName.AnimationSpeed = 200;
            this.inputName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.inputName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.inputName.AutoSizeHeight = true;
            this.inputName.BackColor = System.Drawing.Color.Transparent;
            this.inputName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("inputName.BackgroundImage")));
            this.inputName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.inputName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.inputName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.inputName.BorderColorIdle = System.Drawing.Color.Silver;
            this.inputName.BorderRadius = 1;
            this.inputName.BorderThickness = 1;
            this.inputName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.inputName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.inputName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.inputName.DefaultText = "";
            this.inputName.Enabled = false;
            this.inputName.FillColor = System.Drawing.Color.White;
            this.inputName.HideSelection = true;
            this.inputName.IconLeft = null;
            this.inputName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.inputName.IconPadding = 10;
            this.inputName.IconRight = null;
            this.inputName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.inputName.Lines = new string[0];
            this.inputName.Location = new System.Drawing.Point(217, 37);
            this.inputName.MaxLength = 32767;
            this.inputName.MinimumSize = new System.Drawing.Size(1, 1);
            this.inputName.Modified = false;
            this.inputName.Multiline = false;
            this.inputName.Name = "inputName";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.inputName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.inputName.OnIdleState = stateProperties12;
            this.inputName.Padding = new System.Windows.Forms.Padding(3);
            this.inputName.PasswordChar = '\0';
            this.inputName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.inputName.PlaceholderText = "Enter text";
            this.inputName.ReadOnly = false;
            this.inputName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.inputName.SelectedText = "";
            this.inputName.SelectionLength = 0;
            this.inputName.SelectionStart = 0;
            this.inputName.ShortcutsEnabled = true;
            this.inputName.Size = new System.Drawing.Size(213, 39);
            this.inputName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.inputName.TabIndex = 1;
            this.inputName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.inputName.TextMarginBottom = 0;
            this.inputName.TextMarginLeft = 3;
            this.inputName.TextMarginTop = 1;
            this.inputName.TextPlaceholder = "Enter text";
            this.inputName.UseSystemPasswordChar = false;
            this.inputName.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(142, 46);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(37, 15);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Cliente";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.VentaCC);
            this.bunifuGroupBox2.Controls.Add(this.dataMove);
            this.bunifuGroupBox2.Controls.Add(this.btnPay);
            this.bunifuGroupBox2.Controls.Add(this.comboSelect);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel8);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel7);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel6);
            this.bunifuGroupBox2.Controls.Add(this.bunifuDatePicker2);
            this.bunifuGroupBox2.Controls.Add(this.bunifuDatePicker1);
            this.bunifuGroupBox2.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(0, 127);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(1184, 408);
            this.bunifuGroupBox2.TabIndex = 1;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Movimientos";
            this.bunifuGroupBox2.Enter += new System.EventHandler(this.bunifuGroupBox2_Enter);
            // 
            // VentaCC
            // 
            this.VentaCC.AllowAnimations = true;
            this.VentaCC.AllowMouseEffects = true;
            this.VentaCC.AllowToggling = false;
            this.VentaCC.AnimationSpeed = 200;
            this.VentaCC.AutoGenerateColors = false;
            this.VentaCC.AutoRoundBorders = false;
            this.VentaCC.AutoSizeLeftIcon = true;
            this.VentaCC.AutoSizeRightIcon = true;
            this.VentaCC.BackColor = System.Drawing.Color.Transparent;
            this.VentaCC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.VentaCC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("VentaCC.BackgroundImage")));
            this.VentaCC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.VentaCC.ButtonText = "cuenta corriente";
            this.VentaCC.ButtonTextMarginLeft = 0;
            this.VentaCC.ColorContrastOnClick = 45;
            this.VentaCC.ColorContrastOnHover = 45;
            this.VentaCC.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.VentaCC.CustomizableEdges = borderEdges1;
            this.VentaCC.DialogResult = System.Windows.Forms.DialogResult.None;
            this.VentaCC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.VentaCC.DisabledFillColor = System.Drawing.Color.Empty;
            this.VentaCC.DisabledForecolor = System.Drawing.Color.Empty;
            this.VentaCC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.VentaCC.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.VentaCC.ForeColor = System.Drawing.Color.White;
            this.VentaCC.IconLeft = null;
            this.VentaCC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.VentaCC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.VentaCC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.VentaCC.IconMarginLeft = 11;
            this.VentaCC.IconPadding = 10;
            this.VentaCC.IconRight = null;
            this.VentaCC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.VentaCC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.VentaCC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.VentaCC.IconSize = 25;
            this.VentaCC.IdleBorderColor = System.Drawing.Color.Empty;
            this.VentaCC.IdleBorderRadius = 0;
            this.VentaCC.IdleBorderThickness = 0;
            this.VentaCC.IdleFillColor = System.Drawing.Color.Empty;
            this.VentaCC.IdleIconLeftImage = null;
            this.VentaCC.IdleIconRightImage = null;
            this.VentaCC.IndicateFocus = false;
            this.VentaCC.Location = new System.Drawing.Point(36, 298);
            this.VentaCC.Name = "VentaCC";
            this.VentaCC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.VentaCC.OnDisabledState.BorderRadius = 1;
            this.VentaCC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.VentaCC.OnDisabledState.BorderThickness = 1;
            this.VentaCC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.VentaCC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.VentaCC.OnDisabledState.IconLeftImage = null;
            this.VentaCC.OnDisabledState.IconRightImage = null;
            this.VentaCC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.VentaCC.onHoverState.BorderRadius = 1;
            this.VentaCC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.VentaCC.onHoverState.BorderThickness = 1;
            this.VentaCC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.VentaCC.onHoverState.ForeColor = System.Drawing.Color.White;
            this.VentaCC.onHoverState.IconLeftImage = null;
            this.VentaCC.onHoverState.IconRightImage = null;
            this.VentaCC.OnIdleState.BorderColor = System.Drawing.Color.SpringGreen;
            this.VentaCC.OnIdleState.BorderRadius = 1;
            this.VentaCC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.VentaCC.OnIdleState.BorderThickness = 1;
            this.VentaCC.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.VentaCC.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.VentaCC.OnIdleState.IconLeftImage = null;
            this.VentaCC.OnIdleState.IconRightImage = null;
            this.VentaCC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.VentaCC.OnPressedState.BorderRadius = 1;
            this.VentaCC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.VentaCC.OnPressedState.BorderThickness = 1;
            this.VentaCC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.VentaCC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.VentaCC.OnPressedState.IconLeftImage = null;
            this.VentaCC.OnPressedState.IconRightImage = null;
            this.VentaCC.Size = new System.Drawing.Size(173, 39);
            this.VentaCC.TabIndex = 12;
            this.VentaCC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.VentaCC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.VentaCC.TextMarginLeft = 0;
            this.VentaCC.TextPadding = new System.Windows.Forms.Padding(0);
            this.VentaCC.UseDefaultRadiusAndThickness = true;
            this.VentaCC.Click += new System.EventHandler(this.VentaCC_Click);
            // 
            // dataMove
            // 
            this.dataMove.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataMove.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataMove.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataMove.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataMove.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataMove.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataMove.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataMove.ColumnHeadersHeight = 40;
            this.dataMove.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataMove.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataMove.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataMove.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataMove.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataMove.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataMove.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataMove.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataMove.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataMove.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataMove.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataMove.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataMove.CurrentTheme.Name = null;
            this.dataMove.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataMove.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataMove.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataMove.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataMove.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataMove.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataMove.EnableHeadersVisualStyles = false;
            this.dataMove.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataMove.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataMove.HeaderForeColor = System.Drawing.Color.White;
            this.dataMove.Location = new System.Drawing.Point(278, 83);
            this.dataMove.Name = "dataMove";
            this.dataMove.RowHeadersVisible = false;
            this.dataMove.RowTemplate.Height = 40;
            this.dataMove.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataMove.Size = new System.Drawing.Size(894, 302);
            this.dataMove.TabIndex = 6;
            this.dataMove.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dataMove.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataMove_CellClick);
            // 
            // btnPay
            // 
            this.btnPay.AllowAnimations = true;
            this.btnPay.AllowMouseEffects = true;
            this.btnPay.AllowToggling = false;
            this.btnPay.AnimationSpeed = 200;
            this.btnPay.AutoGenerateColors = false;
            this.btnPay.AutoRoundBorders = false;
            this.btnPay.AutoSizeLeftIcon = true;
            this.btnPay.AutoSizeRightIcon = true;
            this.btnPay.BackColor = System.Drawing.Color.Transparent;
            this.btnPay.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnPay.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPay.BackgroundImage")));
            this.btnPay.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPay.ButtonText = "Pagar";
            this.btnPay.ButtonTextMarginLeft = 0;
            this.btnPay.ColorContrastOnClick = 45;
            this.btnPay.ColorContrastOnHover = 45;
            this.btnPay.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnPay.CustomizableEdges = borderEdges2;
            this.btnPay.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPay.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPay.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnPay.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnPay.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPay.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnPay.ForeColor = System.Drawing.Color.White;
            this.btnPay.IconLeft = null;
            this.btnPay.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPay.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPay.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPay.IconMarginLeft = 11;
            this.btnPay.IconPadding = 10;
            this.btnPay.IconRight = null;
            this.btnPay.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPay.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPay.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPay.IconSize = 25;
            this.btnPay.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnPay.IdleBorderRadius = 0;
            this.btnPay.IdleBorderThickness = 0;
            this.btnPay.IdleFillColor = System.Drawing.Color.Empty;
            this.btnPay.IdleIconLeftImage = null;
            this.btnPay.IdleIconRightImage = null;
            this.btnPay.IndicateFocus = false;
            this.btnPay.Location = new System.Drawing.Point(36, 239);
            this.btnPay.Name = "btnPay";
            this.btnPay.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPay.OnDisabledState.BorderRadius = 1;
            this.btnPay.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPay.OnDisabledState.BorderThickness = 1;
            this.btnPay.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPay.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPay.OnDisabledState.IconLeftImage = null;
            this.btnPay.OnDisabledState.IconRightImage = null;
            this.btnPay.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPay.onHoverState.BorderRadius = 1;
            this.btnPay.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPay.onHoverState.BorderThickness = 1;
            this.btnPay.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPay.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPay.onHoverState.IconLeftImage = null;
            this.btnPay.onHoverState.IconRightImage = null;
            this.btnPay.OnIdleState.BorderColor = System.Drawing.Color.SpringGreen;
            this.btnPay.OnIdleState.BorderRadius = 1;
            this.btnPay.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPay.OnIdleState.BorderThickness = 1;
            this.btnPay.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnPay.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPay.OnIdleState.IconLeftImage = null;
            this.btnPay.OnIdleState.IconRightImage = null;
            this.btnPay.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPay.OnPressedState.BorderRadius = 1;
            this.btnPay.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPay.OnPressedState.BorderThickness = 1;
            this.btnPay.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPay.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPay.OnPressedState.IconLeftImage = null;
            this.btnPay.OnPressedState.IconRightImage = null;
            this.btnPay.Size = new System.Drawing.Size(173, 39);
            this.btnPay.TabIndex = 11;
            this.btnPay.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPay.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPay.TextMarginLeft = 0;
            this.btnPay.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPay.UseDefaultRadiusAndThickness = true;
            this.btnPay.Click += new System.EventHandler(this.btnPay_Click);
            // 
            // comboSelect
            // 
            this.comboSelect.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboSelect.FormattingEnabled = true;
            this.comboSelect.Location = new System.Drawing.Point(550, 38);
            this.comboSelect.Name = "comboSelect";
            this.comboSelect.Size = new System.Drawing.Size(246, 23);
            this.comboSelect.TabIndex = 5;
            this.comboSelect.SelectedIndexChanged += new System.EventHandler(this.comboSelect_SelectedIndexChanged);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(461, 41);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(79, 15);
            this.bunifuLabel8.TabIndex = 4;
            this.bunifuLabel8.Text = "Tipo operación";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(25, 161);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(33, 15);
            this.bunifuLabel7.TabIndex = 3;
            this.bunifuLabel7.Text = "Hasta:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(19, 93);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(35, 15);
            this.bunifuLabel6.TabIndex = 2;
            this.bunifuLabel6.Text = "Desde:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDatePicker2
            // 
            this.bunifuDatePicker2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDatePicker2.BorderRadius = 1;
            this.bunifuDatePicker2.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker2.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker2.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker2.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker2.DisplayWeekNumbers = false;
            this.bunifuDatePicker2.DPHeight = 0;
            this.bunifuDatePicker2.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker2.FillDatePicker = false;
            this.bunifuDatePicker2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDatePicker2.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker2.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker2.Icon")));
            this.bunifuDatePicker2.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker2.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker2.LeftTextMargin = 5;
            this.bunifuDatePicker2.Location = new System.Drawing.Point(25, 182);
            this.bunifuDatePicker2.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker2.Name = "bunifuDatePicker2";
            this.bunifuDatePicker2.Size = new System.Drawing.Size(202, 32);
            this.bunifuDatePicker2.TabIndex = 1;
            // 
            // bunifuDatePicker1
            // 
            this.bunifuDatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.BorderRadius = 1;
            this.bunifuDatePicker1.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.DisplayWeekNumbers = false;
            this.bunifuDatePicker1.DPHeight = 0;
            this.bunifuDatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker1.FillDatePicker = false;
            this.bunifuDatePicker1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDatePicker1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker1.Icon")));
            this.bunifuDatePicker1.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker1.LeftTextMargin = 5;
            this.bunifuDatePicker1.Location = new System.Drawing.Point(25, 114);
            this.bunifuDatePicker1.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker1.Name = "bunifuDatePicker1";
            this.bunifuDatePicker1.Size = new System.Drawing.Size(202, 32);
            this.bunifuDatePicker1.TabIndex = 0;
            // 
            // numberVta
            // 
            this.numberVta.AcceptsReturn = false;
            this.numberVta.AcceptsTab = false;
            this.numberVta.AnimationSpeed = 200;
            this.numberVta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.numberVta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.numberVta.AutoSizeHeight = true;
            this.numberVta.BackColor = System.Drawing.Color.Transparent;
            this.numberVta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("numberVta.BackgroundImage")));
            this.numberVta.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.numberVta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.numberVta.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.numberVta.BorderColorIdle = System.Drawing.Color.Silver;
            this.numberVta.BorderRadius = 1;
            this.numberVta.BorderThickness = 1;
            this.numberVta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.numberVta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numberVta.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.numberVta.DefaultText = "";
            this.numberVta.Enabled = false;
            this.numberVta.FillColor = System.Drawing.Color.White;
            this.numberVta.HideSelection = true;
            this.numberVta.IconLeft = null;
            this.numberVta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberVta.IconPadding = 10;
            this.numberVta.IconRight = null;
            this.numberVta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberVta.Lines = new string[0];
            this.numberVta.Location = new System.Drawing.Point(113, 574);
            this.numberVta.MaxLength = 32767;
            this.numberVta.MinimumSize = new System.Drawing.Size(1, 1);
            this.numberVta.Modified = false;
            this.numberVta.Multiline = false;
            this.numberVta.Name = "numberVta";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberVta.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.numberVta.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberVta.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberVta.OnIdleState = stateProperties16;
            this.numberVta.Padding = new System.Windows.Forms.Padding(3);
            this.numberVta.PasswordChar = '\0';
            this.numberVta.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.numberVta.PlaceholderText = "Enter text";
            this.numberVta.ReadOnly = false;
            this.numberVta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numberVta.SelectedText = "";
            this.numberVta.SelectionLength = 0;
            this.numberVta.SelectionStart = 0;
            this.numberVta.ShortcutsEnabled = true;
            this.numberVta.Size = new System.Drawing.Size(213, 39);
            this.numberVta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.numberVta.TabIndex = 8;
            this.numberVta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.numberVta.TextMarginBottom = 0;
            this.numberVta.TextMarginLeft = 3;
            this.numberVta.TextMarginTop = 1;
            this.numberVta.TextPlaceholder = "Enter text";
            this.numberVta.UseSystemPasswordChar = false;
            this.numberVta.WordWrap = true;
            // 
            // BtnSendEmail
            // 
            this.BtnSendEmail.AllowAnimations = true;
            this.BtnSendEmail.AllowMouseEffects = true;
            this.BtnSendEmail.AllowToggling = false;
            this.BtnSendEmail.AnimationSpeed = 200;
            this.BtnSendEmail.AutoGenerateColors = false;
            this.BtnSendEmail.AutoRoundBorders = false;
            this.BtnSendEmail.AutoSizeLeftIcon = true;
            this.BtnSendEmail.AutoSizeRightIcon = true;
            this.BtnSendEmail.BackColor = System.Drawing.Color.Transparent;
            this.BtnSendEmail.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnSendEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSendEmail.BackgroundImage")));
            this.BtnSendEmail.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSendEmail.ButtonText = "Envia email";
            this.BtnSendEmail.ButtonTextMarginLeft = 0;
            this.BtnSendEmail.ColorContrastOnClick = 45;
            this.BtnSendEmail.ColorContrastOnHover = 45;
            this.BtnSendEmail.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnSendEmail.CustomizableEdges = borderEdges3;
            this.BtnSendEmail.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSendEmail.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSendEmail.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnSendEmail.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnSendEmail.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSendEmail.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnSendEmail.ForeColor = System.Drawing.Color.White;
            this.BtnSendEmail.IconLeft = null;
            this.BtnSendEmail.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSendEmail.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSendEmail.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSendEmail.IconMarginLeft = 11;
            this.BtnSendEmail.IconPadding = 10;
            this.BtnSendEmail.IconRight = null;
            this.BtnSendEmail.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSendEmail.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSendEmail.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSendEmail.IconSize = 25;
            this.BtnSendEmail.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnSendEmail.IdleBorderRadius = 0;
            this.BtnSendEmail.IdleBorderThickness = 0;
            this.BtnSendEmail.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnSendEmail.IdleIconLeftImage = null;
            this.BtnSendEmail.IdleIconRightImage = null;
            this.BtnSendEmail.IndicateFocus = false;
            this.BtnSendEmail.Location = new System.Drawing.Point(470, 574);
            this.BtnSendEmail.Name = "BtnSendEmail";
            this.BtnSendEmail.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSendEmail.OnDisabledState.BorderRadius = 1;
            this.BtnSendEmail.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSendEmail.OnDisabledState.BorderThickness = 1;
            this.BtnSendEmail.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSendEmail.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSendEmail.OnDisabledState.IconLeftImage = null;
            this.BtnSendEmail.OnDisabledState.IconRightImage = null;
            this.BtnSendEmail.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnSendEmail.onHoverState.BorderRadius = 1;
            this.BtnSendEmail.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSendEmail.onHoverState.BorderThickness = 1;
            this.BtnSendEmail.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnSendEmail.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnSendEmail.onHoverState.IconLeftImage = null;
            this.BtnSendEmail.onHoverState.IconRightImage = null;
            this.BtnSendEmail.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnSendEmail.OnIdleState.BorderRadius = 1;
            this.BtnSendEmail.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSendEmail.OnIdleState.BorderThickness = 1;
            this.BtnSendEmail.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnSendEmail.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSendEmail.OnIdleState.IconLeftImage = null;
            this.BtnSendEmail.OnIdleState.IconRightImage = null;
            this.BtnSendEmail.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnSendEmail.OnPressedState.BorderRadius = 1;
            this.BtnSendEmail.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSendEmail.OnPressedState.BorderThickness = 1;
            this.BtnSendEmail.OnPressedState.FillColor = System.Drawing.SystemColors.ButtonShadow;
            this.BtnSendEmail.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnSendEmail.OnPressedState.IconLeftImage = null;
            this.BtnSendEmail.OnPressedState.IconRightImage = null;
            this.BtnSendEmail.Size = new System.Drawing.Size(173, 39);
            this.BtnSendEmail.TabIndex = 9;
            this.BtnSendEmail.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnSendEmail.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSendEmail.TextMarginLeft = 0;
            this.BtnSendEmail.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnSendEmail.UseDefaultRadiusAndThickness = true;
            // 
            // BtnPrint
            // 
            this.BtnPrint.AllowAnimations = true;
            this.BtnPrint.AllowMouseEffects = true;
            this.BtnPrint.AllowToggling = false;
            this.BtnPrint.AnimationSpeed = 200;
            this.BtnPrint.AutoGenerateColors = false;
            this.BtnPrint.AutoRoundBorders = false;
            this.BtnPrint.AutoSizeLeftIcon = true;
            this.BtnPrint.AutoSizeRightIcon = true;
            this.BtnPrint.BackColor = System.Drawing.Color.Transparent;
            this.BtnPrint.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnPrint.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnPrint.BackgroundImage")));
            this.BtnPrint.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnPrint.ButtonText = "Imprimir";
            this.BtnPrint.ButtonTextMarginLeft = 0;
            this.BtnPrint.ColorContrastOnClick = 45;
            this.BtnPrint.ColorContrastOnHover = 45;
            this.BtnPrint.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnPrint.CustomizableEdges = borderEdges4;
            this.BtnPrint.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnPrint.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnPrint.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnPrint.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnPrint.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnPrint.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BtnPrint.ForeColor = System.Drawing.Color.White;
            this.BtnPrint.IconLeft = null;
            this.BtnPrint.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnPrint.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnPrint.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnPrint.IconMarginLeft = 11;
            this.BtnPrint.IconPadding = 10;
            this.BtnPrint.IconRight = null;
            this.BtnPrint.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnPrint.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnPrint.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnPrint.IconSize = 25;
            this.BtnPrint.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnPrint.IdleBorderRadius = 0;
            this.BtnPrint.IdleBorderThickness = 0;
            this.BtnPrint.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnPrint.IdleIconLeftImage = null;
            this.BtnPrint.IdleIconRightImage = null;
            this.BtnPrint.IndicateFocus = false;
            this.BtnPrint.Location = new System.Drawing.Point(845, 574);
            this.BtnPrint.Name = "BtnPrint";
            this.BtnPrint.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnPrint.OnDisabledState.BorderRadius = 1;
            this.BtnPrint.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnPrint.OnDisabledState.BorderThickness = 1;
            this.BtnPrint.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnPrint.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnPrint.OnDisabledState.IconLeftImage = null;
            this.BtnPrint.OnDisabledState.IconRightImage = null;
            this.BtnPrint.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnPrint.onHoverState.BorderRadius = 1;
            this.BtnPrint.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnPrint.onHoverState.BorderThickness = 1;
            this.BtnPrint.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnPrint.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnPrint.onHoverState.IconLeftImage = null;
            this.BtnPrint.onHoverState.IconRightImage = null;
            this.BtnPrint.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnPrint.OnIdleState.BorderRadius = 1;
            this.BtnPrint.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnPrint.OnIdleState.BorderThickness = 1;
            this.BtnPrint.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnPrint.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnPrint.OnIdleState.IconLeftImage = null;
            this.BtnPrint.OnIdleState.IconRightImage = null;
            this.BtnPrint.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnPrint.OnPressedState.BorderRadius = 1;
            this.BtnPrint.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnPrint.OnPressedState.BorderThickness = 1;
            this.BtnPrint.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnPrint.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnPrint.OnPressedState.IconLeftImage = null;
            this.BtnPrint.OnPressedState.IconRightImage = null;
            this.BtnPrint.Size = new System.Drawing.Size(173, 39);
            this.BtnPrint.TabIndex = 10;
            this.BtnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnPrint.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnPrint.TextMarginLeft = 0;
            this.BtnPrint.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnPrint.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(117, 559);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(74, 15);
            this.bunifuLabel9.TabIndex = 7;
            this.bunifuLabel9.Text = "venta numero";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cuenta_corriente
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1184, 646);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.BtnPrint);
            this.Controls.Add(this.BtnSendEmail);
            this.Controls.Add(this.numberVta);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Name = "cuenta_corriente";
            this.Text = "cuenta corriente";
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataMove)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox inputEmail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox inputDNI;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox inputName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel lblSaldo;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuDataGridView dataMove;
        private System.Windows.Forms.ComboBox comboSelect;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker2;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private Bunifu.UI.WinForms.BunifuTextBox numberVta;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSendEmail;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnPrint;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPay;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton VentaCC;
    }
}